project:
  type: website

execute: 
  freeze: true

website:
  title: "**THOMAS ZWAGERMAN**"
  cookie-consent:
    type: express
    style: headline
    palette: dark
  google-analytics: 
    tracking-id: "G-81ENW8BPLM"
    anonymize-ip: true
  favicon: images/TZ-beige.png
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - portfolio.qmd
      - contact.qmd
      
  page-footer:
    background: "#f5f5f1"
    left: |
      Copyright &copy; 2023 Thomas Zwagerman

format:
  html:
    grid:
      body-width: 1300px
      gutter-width: 1.5rem
    theme: custom.scss
    css: styles.css
    toc: true

editor: visual

