project:
  type: website

execute:
  freeze: auto
  
website:
  title: "Thomas Zwagerman"
  google-analytics: 
    tracking-id: "G-81ENW8BPLM"
    storage: none
    anonymize-ip: true
  favicon: images/TZ-beige.png
  navbar:
    background: "#003D73"
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Software Packages"
        file: software.qmd
      - text: "Publications"
        file: publications.qmd
      - text: "Contact"
        file: contact.qmd
  page-footer:
    left: "© 2024 Thomas Zwagerman"
    right: 
      - icon: github
        href: https://github.com/thomaszwagerman
      - icon: orcid
        href: https://orcid.org/0009-0003-3742-3234

format:
  html:
    theme:
      dark: [darkly, custom.scss]
      light: [flatly, custom.scss]
    css: styles.css
    toc: true
    toc-location: right
    page-layout: full
    fontsize: 1.1em
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">
